[tool.mypy]
files = "src/*.py"
show_error_codes = true
pretty = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
check_untyped_defs = true
implicit_reexport = false

[[tool.mypy.overrides]]
module = [
    "dash.*",
    "dash_bootstrap_components",
    "dash_mantine_components",
    "user_agents",
    "requests",
    "pyrostorage",
    "dateutil",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["src/"]
skip_glob = ["**/__init__.py"]

[tool.pydocstyle]
select = "D300,D301,D417"
match = ".*\\.py"

[tool.coverage.run]
source = ["src"]

[tool.black]
line-length = 120
target-version = ['py38']
